---
- hosts: localhost
  gather_facts: false


  tasks:
  - name : Create a Vm clone
    vmware_guest:
      hostname: 192.168.100.53
      username: administrator@vsphere.local
      password: Neo233@ba
      validate_certs: no
      datacenter: BLR
      state: poweredon
      folder: New-vm/test
      template: bipul
      name: bipul1
      cluster: Cluster
      #networks:
      #- name: VM Network
      #  ip: 192.168.10.11
      #  netmask: 255.255.255.0
      #wait_for_ip_address: True
      #customization:
           #domain: "{{ guest_domain }}"
           #dns_servers:
           # - 8.9.9.9
           # - 7.8.8.9
      #dns_suffix:
      #  - example.com
      #  - example2.com
    delegate_to: localhost
